# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xeno < Formula
  desc "A CLI tool designed for the Xeno-Canto Website"
  homepage "https://github.com/siansiansu/go-xeno"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/siansiansu/go-xeno/releases/download/v1.0.3/go-xeno_Darwin_x86_64.tar.gz"
      sha256 "1406c561d251a3d935f102e3a3340f49befb72f02223fa1cc29f34359162ec57"

      def install
        bin.install "xeno"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/siansiansu/go-xeno/releases/download/v1.0.3/go-xeno_Darwin_arm64.tar.gz"
      sha256 "f2c776b381a7dbc9f7d54f73aa6fe87d175ca4857027e45d503352971fef6e53"

      def install
        bin.install "xeno"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/siansiansu/go-xeno/releases/download/v1.0.3/go-xeno_Linux_arm64.tar.gz"
      sha256 "85de296521416e3c64e28486f1b104d575724843802c8d0ff6e6f619a9408d0c"

      def install
        bin.install "xeno"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/siansiansu/go-xeno/releases/download/v1.0.3/go-xeno_Linux_x86_64.tar.gz"
      sha256 "02e34b15289300c763f4975fc98c7d976d0de0eb05e58bb25f46838b378339c0"

      def install
        bin.install "xeno"
      end
    end
  end
end
