# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xeno < Formula
  desc ""
  homepage "https://github.com/siansiansu/go-xeno"
  version "1.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/siansiansu/go-xeno/releases/download/v1.1.1/go-xeno_Darwin_arm64.tar.gz"
      sha256 "1974f6d65d751de614624352285261040e89366eb20d6db812ec3523f156a9b5"

      def install
        bin.install "xeno"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/siansiansu/go-xeno/releases/download/v1.1.1/go-xeno_Darwin_x86_64.tar.gz"
      sha256 "59b1cc41542b8f84b89b59d117f778ec54ba8f51f105247e776f4f8c713da73c"

      def install
        bin.install "xeno"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/siansiansu/go-xeno/releases/download/v1.1.1/go-xeno_Linux_arm64.tar.gz"
      sha256 "868e7f3c9a754499069dde4c55821f27d3a9f2f798637929017c8d235dacae44"

      def install
        bin.install "xeno"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/siansiansu/go-xeno/releases/download/v1.1.1/go-xeno_Linux_x86_64.tar.gz"
      sha256 "74b3bfa41f307e1bd63d41763c67e2f604be81421c38f557748ee4e56f74ab2b"

      def install
        bin.install "xeno"
      end
    end
  end
end
